services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_SERVER=${POSTGRESQL_SERVER}
      - POSTGRESQL_PORT=${POSTGRESQL_PORT}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
      - DOMAIN=${DOMAIN}
      - ENVIRONMENT=${ENVIRONMENT}
      - BACKEND_CORS_ORIGINS=${BACKEND_CORS_ORIGINS}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    networks:
      - docker-fastapi-base
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: bitnami/postgresql:latest
    platform: linux/amd64
    ports:
      - 5432:5432
    restart: always
    volumes:
      - postgres_data:/bitnami/postgresql
    environment:
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRES_USER=${POSTGRESQL_USERNAME}
      - POSTGRES_DB=${POSTGRESQL_DATABASE}
    networks:
      - docker-fastapi-base

volumes:
  postgres_data:

networks:
  docker-fastapi-base:
    driver: bridge
